README.md, maven/maven.bzl, test/test_workspace/BUILD.bazel, test/test_workspace/WORKSPACE, test/test_workspace/build_substitution_templates.bzl, test/test_workspace/java/foo/BUILD.bazel, test/test_workspace/java/foo/Foo.java, test/test_workspace/javatests/foo/BUILD.bazel, test/test_workspace/javatests/foo/FooTest.java
Adds a mechanism to specify build file snippets to substitute for the auto-generated rule for a given artifact in the maven repo.
This ends up allowing things like replacing a naive java library/import with a java_plugin target, and a java_library which exports it.  It's a naive string substitution (which can be made richer with Starlark's pythonic string template formatting feature).
Also add more articulated tests, including using dagger (and a substituted build file snippet to export the annotation processor).
=> Add a mechanism to specify build file snippets to substitute for the naive maven import rule.

maven/artifacts.bzl, maven/maven.bzl
Also remove some extra "just in case" bits of the "annotated" artifact that aren't yet needed (YAGNI)
A key factoring out is the separation of parsing the artifact spec from annotating it with computed properties from those elements (such as paths).  The reason for this is to allow for much cheaper artifact parsing (basic split/destructuring) in some cases where we don't need the extra computed paths.  That's not needed yet but will be used in a planned (and being coded) feature, and it's a good logical separation anyway.
=> Refactor the rules to prepare for more complex features.

maven/artifacts.bzl, maven/maven.bzl, maven/poms.bzl, maven/sets.bzl, maven/utils.bzl, test/test_workspace/WORKSPACE, test/test_workspace/build_substitution_templates.bzl
Generate inter-artifact dependencies in the bazel BUILD files, inferred from their .pom files' metadata.  These all resolve through the same specified repository, so interactions between multiple `maven_repository_specification` declarations will need to be manually inserted via the `build_substitutions` mechanism, if relevant.
Fixes #4 
It's worth noting that this PR increases the configuration burden for doing things like wrapping dagger with an exported_plugins attributed wrapper rule, because doing so introduces build cycles in the dependency relationships inferred from the pom files.  This is addressable (verbosely) using the build_substitution mechanism, but a more supple mechanism (e.g. #9) will be needed to reduce the verbosity.  The trade-off here is that every other artifact …
=> Generate inter-artifact dependencies in the bazel BUILD files.

README.md, maven/maven.bzl, maven/utils.bzl, test/test_workspace/WORKSPACE, test/test_workspace/build_substitution_templates.bzl
Fix #9 by doing what it says. Introduce a mechanism to allow substitution of inferred dependency lines, so you can freely change them with `build_subtitutions` and have the rest of the package construct the correct deps graph.
=> Surgical dependency target rewriting

maven/maven.bzl, maven/poms.bzl
Extract out the logic for 'should we include this dep' into its own method, for clarity, and in the process fix the rather catastrophic set of erroneous hard-coded values that render this feature non-functional.
Fixes #17.
=> Fix handling of optional, non-compile scopes, and system_path style deps. 

maven/maven.bzl, maven/poms.bzl, maven/tests/all_tests.bzl, maven/tests/poms_test.bzl, maven/tests/xml_test.bzl, maven/utils.bzl, maven/xml.bzl
This doesn't (yet) process properties, dependencyManagement sections, or parent poms,
but is a prerequisite of those features.
The parser is a generally complete xml parser, with some specific limitations, namely
it doesn't preserve attributes (but does parse them out) since POM files don't use
attributes. It also doesn't support xml namespaces, drops comments, and does not support
mixed content (xml elements with both non-whitespace text and child-elements). There is
no reason it could not support any of these, but these are not necessary for processing
pom.xml files.
It also has no xpath or equivalent querying system, and performs only minimal in-process
validation. It may accept invalid XML documents (though it does reject unbalanced xml
elements).
This commit also hooks up the new …
=> Add an XML parser, and extract the dependency information from the node tree.

maven/maven.bzl, maven/tests/all_tests.bzl, maven/tests/maven_test.bzl, test/test_workspace/WORKSPACE
Rework the API for maven_repository_specification to allow each artifact to have a property dictionary attached.  The first two properties supported are sha256 (and this replaces just passing a string as the sha) and insecure, which replaces the insecure_artifacts approach, by making you just add a property to it if you don't include the sha.  This also allows for later expansion of the feature set for per-artifact manipulation.  This could replace build_substitutions also, but that will happen in a later commit.
Also fixes the test rig a bit, to make it so that a missing declaration of a suite will be caught.  Minor validation, but helpful.
Lastly, support the older configuration style, but print deprecation messages, and in the process, rework validation of the input and print decent …
=> Support configurable artifact properties.

maven/poms.bzl
This only happens in a failing case, but it makes the error blow up the build, instead of failing in an orderly way.
=> Fix wrong variable usage.  Thanks Starlark.  Types would really help.

maven/maven.bzl, maven/poms.bzl, maven/tests/poms_for_testing.bzl, maven/tests/poms_merging_test.bzl, maven/tests/poms_test.bzl, test/test_workspace/WORKSPACE, test/test_workspace/build_substitution_templates.bzl
As of this commit, the dependencies of a pom can be obtained, incorporating any inherited metadata, any `dependencyManagement` sections, and substituting any properties.  The resulting deps should then be accurate (insofar as the pom.xml files themselves are accurate).  The system can then safely use these deps values to generate a deps list in the bazel workspace representing the maven repository with no corrective substitutions necessary to handle correctly specified pom data. 
Fixes #14 and fixes #15
=> Make the pom processing return the fully inferred dependency information, from a given 'effective' pom.

maven/maven.bzl, test/test_workspace/WORKSPACE
Fixes a name collision where build/ directories generated from groupIds with build in their elements collides with BUILD file reading and writing.
Fixes #38
=> Generate BUILD.bazel instead of BUILD files. 

maven/tests/xml_test.bzl, maven/xml.bzl, test/test_workspace/WORKSPACE
Since some pom.xml files apparently do so, handle `<![CNAME[ ... ]]>`
Also tidy the comment processing, of which this is a peer, so it's a bit more compact. 
Fixes #40
=> Make the parser parse CNAME elements in xml files

maven/maven.bzl
Move the artifact download until after the build file is written, so if there's a download failure, there's still a workspace and build file.  This makes the error a little easier to understand.
=> Move the artifact download until after the build file is written

maven/jvm.bzl, test/test_workspace/WORKSPACE, test/test_workspace/java/foo/BUILD.bazel, test/test_workspace/java/foo/Blah.java, test/test_workspace/java/foo/Foo.java
If B deps on A as a part of API, e.g. inheriting from a class, A must be in the compilation classpath.  This case adds a java_library example and a kt_jvm_library example of just such a case (rxjava2's Flowable and reactive-streaming's Publisher).  This succeeds in the java_library case, so it's clear bazel_maven_repository's construction of a JavaInfo is sound. It fails in kotlin (even java compiled by the kotlin rules' kotlinc invocation) because it has half-baked strict-deps support, and ends up not consuming the proper classpath. Because it fails, it's commented out with a note pointing at the issue bazelbuild/rules_kotlin#132.  This can be commented out at hte point where it's fixed.
This tests for the regression noticed in #54 but doesn't fix it since it's not a bug in this project.
=> Add a case to the test_workspace which proves that the compile-time transitive deps are present.

maven/jvm.bzl, test/test_workspace/build_substitution_templates.bzl, test/test_workspace/java/foo/BUILD.bazel
This is necessary in some cases for workarounds (such as bazelbuild/rules_kotlin#132, or generally supporting convenience exports, such as dagger exporting jsr330, etc.)
=> Add support for exports= to raw_jvm_imports

maven/poms.bzl, maven/tests/poms_test.bzl, test/test_workspace/WORKSPACE
Turns out bool(some_string) does odd things, including returning true on non-empty strings.  Should not have been using magic coercion, but instead needed to test that the content of the string was what Maven interpreted as 'true' and in all other cases return false.
So do that now. Also add a test, and add an example of that with an explanation in the test_workspace.  (can't really test the failure because we can't fail the build-under-test).
Fixes #62
=> Fix boolean coercion of a string

maven/maven.bzl, maven/tests/maven_test.bzl
=> Use the newer respository_ctx.read() API instead of shelling out to 'cat' which doesn't exist on all platforms.

README.md, maven/maven.bzl, maven/tests/maven_test.bzl, test/test_workspace/WORKSPACE
This feature adds a facility for caching pom files in the content addressable (CA) cache. This can be done securely or insecurely.
In secure mode, one adds `pom_sha256` items to each artifact, and they are downloaded with the caching behavior typical of bazel downloads.  Poms not so listed are downloaded anew each time, displaying their SHA hashes on the console, as before.  Note that there is no facility (at this time) of specifying the sha for parent poms, these being different artifacts.  A later feature will add this.
In insecure mode, the user can supply a cache directory (typically something like `.cache/bazel_maven_repository/pom_hashes`) as a repository-level configuration.  In this case, the first time .pom files are downloaded, their sha256 hashes are cached in that directory. …
=> Cache pom files for configured artifacts

maven/maven.bzl, maven/tests/maven_test.bzl, test/test_workspace/WORKSPACE
This should reduce the need for build_snippet usage.
Fixes #74
=> Support dependency exclusions as a first class configuration option.

maven/constants.bzl, maven/fetch.bzl, maven/maven.bzl
This is partly to reduce the size of maven.bzl, but also to make it a bit easier to extract pom fetching into separate per-pom rules and have all that pending code make more sense.
=> Refactor artifact fetching.

maven/artifacts.bzl, maven/constants.bzl, maven/fetch.bzl, maven/globals.bzl, maven/maven.bzl, maven/packaging_type.bzl, maven/poms.bzl, maven/tests/all_tests.bzl, maven/tests/fetch_test.bzl, maven/tests/globals_test.bzl, maven/tests/maven_test.bzl, maven/tests/poms_for_testing.bzl, maven/tests/poms_test.bzl, maven/utils.bzl, maven/xml.bzl, test/test_workspace/WORKSPACE
Discovers the pom packaging type from the pom.xml as-parsed, avoiding the need to specify it in the artifact dictionary (unless a classifier is being used, in which case it must precede the classifier, as that's the standard format of the maven slug).
Also factor out an faux-enum, add testing of the packaging detection, rework pom fetching into individual external workspaces, move common naming into shared functions in globals.bzl, add an android use-case, etc.
This PR also adds a bit more report_progress granularity, in the hopes of having more exposure of the timings of things.
More detail:
The design splits pom handling into two phases.  The first is the fetch itself, which partially parses the pom enough to get the inheritance hierarchy, in order to know what to fetch next.  Then …
=> Infer the packaging type from the pom.

maven/artifacts.bzl, maven/globals.bzl, maven/maven.bzl, maven/tests/all_tests.bzl, maven/tests/strings_test.bzl, maven/utils.bzl, test/test_workspace/WORKSPACE, test/test_workspace/build_substitution_templates.bzl, test/test_workspace/java/blah/BUILD.bazel
Relax some of the name mangling that bazel_maven_repository does, so that artifact_ids that don't have `.` in their names aren't mangled.
In particular, `-` is now not mangled, as a lot of artifact_ids have this, but bazel is perfectly capable of handling this when it comes to targets.
The upshot is that now `com.google.dagger:dagger-compiler:2.24` would be referenced as `@maven//com/google/dagger:dagger-compiler`
Also add a legacy mode, so that projects upgrading can just flag on to have compatibility aliases generated with the old names, while they adjust to the new naming implications.  In the above case, it would result in the following snippet being added to `external/maven/com/google/dagger/BUILD.bazel`:
```
alias(
name = "dagger_compiler",
actual = ":dagger-compiler",
visibility = …
```
=> Relax name mangling of artifact_ids

.travis.yml, README.md, maven/artifacts.bzl, maven/fetch.bzl, maven/globals.bzl, maven/maven.bzl, maven/poms.bzl, maven/tests/fetch_test.bzl, maven/tests/maven_test.bzl, maven/tests/poms_merging_test.bzl, maven/tests/poms_test.bzl, maven/utils.bzl
Also clean up from prior refactorings, notably removing all the annotate() calls which are now superfluous.
=> Convert to using read() (a 0.29+ api).

maven/jetifier.bzl, maven/maven.bzl, maven/poms.bzl
This change covers two aspects:
* Artifact mapping - based on list available here https://developer.android.com/jetpack/androidx/migrate/artifact-mappings all artfiacts "mentioned" in POMs (in dependencies) are mapped to AndroidX artifacts
* Rewriting .jar's and .aar's using jetifier-standalone so they reference (import) correct (Androidx) packages (there is basic/hardcoded support for excluding certain artfiacts, such as android.* or bouncycastle)
> Note: This won't add flagging of the feature on and off, which will come in a subsequent PR.
=> Add support for AndroidX

maven/poms.bzl
Using the length of the `merged` list as an index is incorrect. 
This bug came up when merging `pom.xml` `<properties>`; finding an already-found (e.g.; duplicate/overriding) XML node label leads to a memoized, off-by-one index being used.
To reproduce, attempt to use the `com.sun.activation:javax.activation:1.2.0` artifact ([`pom.xml`](https://repo1.maven.org/maven2/com/sun/activation/javax.activation/1.2.0/javax.activation-1.2.0.pom)). This will bring in parent `pom.xml`s from [`com.sun.activation:all:1.2.0`](https://repo1.maven.org/maven2/com/sun/activation/all/1.2.0/all-1.2.0.pom) and [`net.java:jvnet-parent:1`](https://repo1.maven.org/maven2/net/java/jvnet-parent/1/jvnet-parent-1.pom), the former having a duplicate property (`activation.bundle.symbolicName`) which triggers this.
=> Fix off-by-one IndexError in _merge_leaf_elements

.travis.yml, maven/jetifier.bzl, maven/maven.bzl, maven/poms.bzl, test/test_workspace/WORKSPACE
This pulls in @inez' support from the 1.0.x maintenance branch, and adapts it to the new structure.  It also tidies up a few things about error reporting for missing deps. It also updates the test workspace so it can run against bazel 1.0 (by using the latest kotlin rules)
=> Pull in Jettifier support from the 1.0 side branch. 

maven/maven.bzl, maven/poms.bzl, maven/tests/maven_test.bzl, maven/tests/poms_for_testing.bzl, test/test_workspace/WORKSPACE
Make it so that the jetifier mechanisms (both deps substitution and artifact processing) respect the attribute of the maven_repository_specification() macro.
Also, improve the output of missing deps.
=> Make jetifier support configurable.

maven/jetifier.bzl
Previous version (1.0.0-beta07) of Jetifier was modifying timestamps of files inside JARs which was affecting Bazel cache in a bad way - this version solves this problem.
=> Update Jetifier to 1.0.0-beta08

maven/jetifier.bzl, maven/jvm.bzl, maven/maven.bzl, maven/tests/maven_test.bzl
This ensures that aar contents work the same as standard android_library rules. Will result in a small performance bump for large numbers of maven repositories as the aar will no longer be expanded at build time.
Additional changes:
* ensure that the jars in raw_jvm_import are passed to the runfiles
* runtime cache for repeated fetching pom files
* progress tracking during pom fetching and build file generation.
=> Expand aars during repository creation.

kramer/src/main/kotlin/kramer/FetchArtifactCommand.kt, kramer/src/test/kotlin/kramer/integration/FetchArtifactIntegrationTest.kt
Instead of copying the artifacts from the local cache, attempt links.
Essentially - try a hard-link, failing that a symbolic link, and failing that a straight copy.
Also, don't bother to copy the .aar before we explode it. Just explode it.
=> use links where possible to transfer artifacts.

kramer/WORKSPACE, kramer/src/main/kotlin/kramer/FetchArtifactCommand.kt, kramer/src/main/kotlin/kramer/GenerateMavenRepoCommand.kt, kramer/src/main/kotlin/kramer/Templates.kt, kramer/src/test/kotlin/kramer/JetifierTest.kt, kramer/src/test/kotlin/kramer/integration/FetchArtifactIntegrationTest.kt, kramer/src/test/kotlin/kramer/integration/GenerateMavenRepoIntegrationTest.kt
Upgrades maven-archeologist to 0.0.4 which has sub-artifact fetchign capability.
Uses this to (if possible) download a sources.jar for the given artifact, and propagates it through a filegroup so raw_jvm_import appropriately specifies it. This permits IntelliJ (or anthing else that consumes source_jar metadata to provide the sources to the developer.
Fixes #44
=> Support source jar propagation.

kramer/src/main/kotlin/kramer/FetchArtifactCommand.kt, kramer/src/test/kotlin/kramer/integration/FetchArtifactIntegrationTest.kt, maven/artifacts.bzl, maven/jetifier.bzl, maven/maven.bzl, test/test_workspace/build_substitution_templates.bzl
Changes the filename of the jar (main artifact or extracted aar classes), so that IDE integration shows a more unique and useful entry in its external libraries.
Pattern is now `maven-$packaging-$artifactId-$version-classes.jar`
Packaging isn't strictly needed, but it helps to separate .aar from .jar imports. Guava looks a bit weird as maven-bundle-guava-... but it IS a bundle-type. (thanks OSGI and maven)
fixes #117
=> Improve IDE usability by altering .jar library filename.

kramer/src/main/kotlin/kramer/FetchArtifactCommand.kt, kramer/src/test/kotlin/kramer/integration/FetchArtifactIntegrationTest.kt
fix issue with
```
Exception in thread "main" java.nio.file.NoSuchFileException: /private/var/tmp/_bazel_rogerh/bca1fc867db017ba7535a1fcbc907dfb/external/com_google_android_gms_play_services_base/maven/res/color/common_google_signin_btn_text_dark.xml
at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
at java.nio.file.Files.newOutputStream(Files.java:216)
at kramer.FetchArtifactCommand.unzip(FetchArtifactCommand.kt:209)
at …
```
=> create subdir too on unzipping artifacts

kramer/src/main/kotlin/kramer/GenerateMavenRepoCommand.kt, kramer/src/test/kotlin/kramer/integration/GenerateMavenRepoIntegrationTest.kt, kramer/src/test/kotlin/kramer/integration/test-duplicate-deps-config.json
Fix a problem where a pom may specify a dependency more than once (e.g. in different scopes). Easily handled by making the dependency an ordered set.
Also add a test case.
=> Fix a problem where a pom may specify a dependency more than once.
